spring.application.name=Job-Portal-Backend-Application
spring.datasource.url=jdbc:postgresql://localhost:5432/Backend_Application
spring.datasource.username=postgres
spring.datasource.password=rahul@756

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
jwt.secret=yedaudasdhdhjdhjhdhjdfshjfdhfhjfdghfdsfsdhfdsdshfjfsdhfdshgfsdhgdfshgfshfdjhsfhjdfhjsfdhj
cloudinary.cloud-name=dt2zraezz
cloudinary.api-key=714963953397394
cloudinary.api-secret=vvbySOCODmUTKJPTrxRnSuwzhpM


#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your_email@gmail.com
#spring.mail.password=YOUR_APP_PASSWORD
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

